import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import path from 'node:path';

const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const out = path.resolve('test-results'); await mkdir(out, { recursive: true });
const browser = await chromium.launch({ headless: true, ...(process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {}), args: ['--use-fake-ui-for-media-stream', '--use-fake-device-for-media-stream'] });
const context = await browser.newContext({ viewport: { width: 1440, height: 1100 }, acceptDownloads: true });
await context.addInitScript(() => {
  window.testTracks = [];
  const original = navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);
  navigator.mediaDevices.getUserMedia = async constraints => { const stream = await original(constraints); window.testTracks.push(...stream.getTracks()); return stream; };
});
const page = await context.newPage(), errors = [];
page.on('pageerror', error => errors.push(error.message));
page.on('console', message => { if (message.type() === 'error' && !message.text().includes('favicon')) errors.push(message.text()); });
const idle = () => page.waitForFunction(() => document.getElementById('state-label').textContent === 'マイク未接続' && !document.getElementById('record-button').disabled);
const clickStep = step => page.locator(`[data-step="${step}"]`).click();
try {
  await page.goto('http://127.0.0.1:4317'); await idle();
  await page.screenshot({ path: path.join(out, 'desktop-setup.png'), fullPage: true });
  await page.locator('#voice-name').fill('テスト音声');
  await page.locator('#record-button').click(); await page.waitForFunction(() => document.getElementById('state-label').textContent === 'マイクテスト中');
  await page.waitForFunction(() => document.getElementById('level-db').textContent !== '— dBFS');
  await page.locator('#record-button').click(); await idle();
  assert.ok(await page.evaluate(() => window.testTracks.every(track => track.readyState === 'ended')));
  console.log('PASS: microphone test and release');
  await clickStep('consent');
  assert.equal(await page.locator('#consent-script').textContent(), '私はこの音声の所有者であり、OpenAIがこの音声を使用して音声合成 モデルを作成することを承認します。');
  await page.locator('#record-button').click(); await page.locator('#countdown').waitFor({ state: 'visible' }); await page.locator('#record-button').click(); await idle();
  assert.equal(await page.locator('.take').count(), 0);
  assert.ok(await page.evaluate(() => window.testTracks.every(track => track.readyState === 'ended')));
  console.log('PASS: countdown cancellation retains no recording');
  await page.locator('#record-button').click(); await page.waitForFunction(() => document.getElementById('state-label').textContent === '録音中');
  assert.ok(await page.locator('[data-step="sample"]').isDisabled());
  await page.waitForFunction(() => Number(document.getElementById('time-display').textContent.slice(3)) > 1);
  await page.locator('#record-button').click(); await idle(); await page.locator('.take audio').waitFor();
  assert.equal(await page.locator('.take').count(), 1);
  assert.ok(await page.evaluate(() => window.testTracks.every(track => track.readyState === 'ended')));
  const consentDuration = await page.locator('.take audio').evaluate(async audio => { if (!Number.isFinite(audio.duration)) await new Promise(resolve => audio.addEventListener('loadedmetadata', resolve, { once: true })); return audio.duration; });
  assert.ok(consentDuration > 1 && consentDuration < 4);
  console.log('PASS: consent PCM recording and playback metadata');
  await clickStep('sample'); await page.locator('#record-button').click(); await page.waitForFunction(() => document.getElementById('state-label').textContent === '録音中');
  await page.waitForFunction(() => document.getElementById('take-count').textContent === '1', null, { timeout: 38000 });
  await idle(); assert.match(await page.locator('#notice').textContent(), /29.9秒/);
  const duration = await page.locator('.take audio').evaluate(async audio => { if (!Number.isFinite(audio.duration)) await new Promise(resolve => audio.addEventListener('loadedmetadata', resolve, { once: true })); return audio.duration; });
  assert.ok(Math.abs(duration - 29.9) < .0001);
  await page.screenshot({ path: path.join(out, 'desktop-sample.png'), fullPage: true });
  console.log('PASS: exact 29.9-second auto-stop');
  await page.locator('#record-button').click(); await page.waitForFunction(() => document.getElementById('state-label').textContent === '録音中');
  assert.ok(await page.locator('.take input').isDisabled());
  await page.waitForFunction(() => Number(document.getElementById('time-display').textContent.slice(3)) > 1);
  await page.locator('#record-button').click(); await idle();
  assert.equal(await page.locator('.take').count(), 2);
  await page.getByRole('radio', { name: 'テイク 01 を選択' }).check();
  await page.reload(); await idle(); assert.equal(await page.locator('#voice-name').inputValue(), 'テスト音声');
  await clickStep('sample'); assert.equal(await page.locator('.take').count(), 2); assert.ok(await page.getByRole('radio', { name: 'テイク 01 を選択' }).isChecked());
  console.log('PASS: take selection and IndexedDB restoration');
  await clickStep('export'); assert.ok(await page.locator('#export-button').isDisabled());
  await page.locator('#review-consent').check(); await page.locator('#review-quality').check();
  await page.screenshot({ path: path.join(out, 'desktop-export.png'), fullPage: true });
  const downloadPromise = page.waitForEvent('download'); await page.locator('#export-button').click(); const download = await downloadPromise; await download.saveAs(path.join(out, 'recording-set.zip'));
  assert.match(download.suggestedFilename(), /テスト音声_voice-recordings.zip/);
  console.log('PASS: reviewed recording ZIP download');
  await page.setViewportSize({ width: 390, height: 844 }); await clickStep('consent');
  await page.screenshot({ path: path.join(out, 'mobile-consent.png'), fullPage: true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  console.log('PASS: mobile viewport has no horizontal overflow');
  await clickStep('sample'); await page.getByRole('button', { name: 'テイク 2 を削除' }).click(); await page.getByRole('button', { name: 'テイク 2 を削除' }).click();
  await page.waitForFunction(() => document.querySelectorAll('.take').length === 1);
  assert.equal(await page.locator('.take').count(), 1);
  console.log('PASS: individual take deletion');
  assert.deepEqual(errors, []);
} finally { await browser.close(); }
